### ISSUE TITLE
       fs2020 label not found. KEY_ELEVATOR_TRIM_DISABLED_TOGGLE context PLANE device SaitekX56Throttle            

### ISSUE THREAD

**Issue by rholder613** [ankurkotwal/MetaRefCard#5]
Error message returned from generator:

-       fs2020 label not found. KEY_ELEVATOR_TRIM_DISABLED_TOGGLE context PLANE device SaitekX56Throttle
      
Full text of inputprofile_xxx ([XML textfile]https://github.com/ankurkotwal/MetaRefCard/files/5493999/inputprofile_0903700928.txt))
 for X56 Saitek Rhino is attached for further analysis.

CMDR Trium

**Comment by ankurkotwal** [comment]
Thanks for reporting the issue. MRC still doesn't have all the strings from the game but I'm adding them as they pop up. The change will go live shortly (bundling a few updates)

**Comment by ankurkotwal** [comment]
New release is now live with this fix. Thanks again for reporting the bug. I hope you're finding MetaRefCard useful.
