### ISSUE TITLE
Extreme 3D Pro- Throttle Paddle Not Mapped

### ISSUE THREAD

**Issue by Toneking77** [ankurkotwal/MetaRefCard#6]
**Describe the bug**
All functions were mapped correctly except the throttle paddle.  Throttle paddle remained blank.

**To Reproduce**
I will attach the file below that I used when I ran the app.

**Expected behavior**
Throttle function would be shown on the output diagram.

**Screenshots**
Logitech Extreme 3D Pro Config (https://user-images.githubusercontent.com/68136616/99197307-ba8b4d80-275f-11eb-9768-5c6514d9407c.jpg)

**Device(s) (please complete the following information):**
 Logitech Extreme 3D Pro

**Game that config file is from:**
 - Name: Flight Simulator 2020
 - Version 1.10.11.0

**Additional context**
[104B06ECC06F470A9B75C5E1C055E59E.zip]

(https://github.com/ankurkotwal/MetaRefCard/files/5543162/104B06ECC06F470A9B75C5E1C055E59E.zip)

Thank you for your time and energy!  Greatly appreciated.

**Comment by ankurkotwal** [comment]
Thanks for raising this issue. I'm looking into it but one thing that will help make it quicker is to know what game input the throttle function is mapped to. When I read the game file myself, each game input is mapped on the image you generated so I'm a bit puzzled.

**Comment by ankurkotwal** [comment]
Hi @Toneking77 ,
Just wanted to check if you could confirm this?

**Comment by ankurkotwal** [comment]
Closing due to lack of response.
